services:
  flask_app:
    container_name: flask_app
    image: claudiocassimiro/flask_app:1.0.0
    env_file:
      - .env
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - flask_db
    networks:
      - app_network
  
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
    - app_network

  flask_db:
    container_name: flask_db
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/database
    networks:
      - app_network

volumes:
  pgdata: {}
  ollama_data:

networks:
  app_network:
    driver: bridge
